function [keys, elements] = create_empty_elements(DIR,bird_exper_name)
    % creates the basic structures for annotating all wav files in DIR
    % input the bird's name in bird_exper_name
    elements = {};
    d = dir([DIR '/*.wav']);
    keys = {d.name};
    exper = struct('birdname',bird_exper_name,'expername','Recording from Canary',...
            'desiredInSampRate',48000,'audioCh',0','sigCh',[],'datecreated',date,'researcher','YC');
    for cnt = 1:numel(keys)
        base_struct = struct('exper',exper, ...
                             'filenum',sprintf('%04d',cnt), ...
                             'segAbsStartTimes',[], ...
                             'segFileStartTimes',[], ...
                             'segFileEndTimes',[], ...
                             'segType',[], ...
                             'fs',48000, ...
                             'drugstatus', 'No Drug', ...
                             'directstatus', 'Undirected');
         elements = {elements{:} base_struct};
    end
end